---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# arcgis

<!-- badges: start -->
<!-- badges: end -->

**NOTE**: under active development! Feedback welcome via issues. 

arcgis is a metapackage that loads ArcGIS location services packages. This includes [`{arcgislayers}`](https://github.com/R-ArcGIS/arcgislayers), and [`{arcgisutils}`](https://github.com/R-ArcGIS/arcgisutils).

Please refer to [`arcgislayers`](https://r.esri.com/arcgislayers/) package site for examples. 

## Installation

You can install the development version of arcgis from [GitHub](https://github.com/) with:

``` r
# install.packages("remotes")
remotes::install_github("R-ArcGIS/arcgis")
```

## Example



```{r example}
library(arcgis)

health_rankings_url <- "https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/2022_County_Health_Rankings/FeatureServer"

arc_open(health_rankings_url)
```
